FROM alpine

LABEL maintainer="kit101 <qkssk1711@163.com>" \
  org.label-schema.name="Drone Plugin Gitee Pulls" \
  org.label-schema.vendor="kit101" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-plugin-gitee-pulls /bin/

ADD release/linux/amd64/docker-entrypoint.sh /

ENTRYPOINT ["sh", "/docker-entrypoint.sh"]
